<?php

namespace App\Http\Controllers\API\Client\v1;

use App\Favorites;
use App\Http\Controllers\BaseAPIController;
use App\Repositories\AppRepositoryImpl;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientFavoriteController extends BaseAPIController
{
    public function __construct(AppRepositoryImpl $appRepository)
    {
        $this->appRepository = $appRepository;
        $this->model = new Favorites();
    }

    public function index(){
        if (!isset(auth()->user()->contact->id))
            return $this->response(null,'برای تکمیل پروفایل شما نیاز دارید تا اطلاعات تماس خود را وارد کرده باشید',403);
        return Favorites::where('contact_id',auth()->user()->contact->id??null)->paginate();
    }
    public function show($id){
        if (!isset(auth()->user()->contact->id))
            return $this->response(null,'برای تکمیل پروفایل شما نیاز دارید تا اطلاعات تماس خود را وارد کرده باشید',403);
        return $this->response(Favorites::where('contact_id',auth()->user()->contact->id??null)->where('id',$id)->first());
    }
    public function update($id){
        if (!isset(auth()->user()->contact->id))
            return $this->response(null,'برای تکمیل پروفایل شما نیاز دارید تا اطلاعات تماس خود را وارد کرده باشید',403);
        if (Favorites::where('contact_id',auth()->user()->contact->id??null)->where('id',$id)->count() == 0)
            return abort(404);
     return parent::update($id); // TODO: Change the autogenerated stub
    }
    public function store(){
        if (!isset(auth()->user()->contact->id))
            return $this->response(null,'برای تکمیل پروفایل شما نیاز دارید تا اطلاعات تماس خود را وارد کرده باشید',403);
        \request()->request->add(['contact_id'=>auth()->user()->contact->id]);
        return parent::store(); // TODO: Change the autogenerated stub
    }
    public function destroy($id){
        if (!isset(auth()->user()->contact->id))
            return $this->response(null,'برای تکمیل پروفایل شما نیاز دارید تا اطلاعات تماس خود را وارد کرده باشید',403);
        if (Favorites::where('contact_id',auth()->user()->contact->id??null)->where('id',$id)->count() == 0)
            return abort(404);
        return parent::destroy($id); // TODO: Change the autogenerated stub
    }
    protected function validationRules(){
        return [
            'contact_id'=>[],
            'title'=>['required'],
            'description'=>[],
            'number'=>['required'],
            'percent'=>[],
            'type'=>[],
            'state'=>[],
        ];
    }
    protected function validationAttributes(){
     return parent::validationAttributes(); // TODO: Change the autogenerated stub
    }
    protected function validationMessages(){
     return parent::validationMessages(); // TODO: Change the autogenerated stub
    }
}
