<?php

namespace App\Http\Controllers;


use App\Contact;
use App\ContactTag;
use App\CTag;
use App\Person;
use App\Repositories\Interfaces\AppRepository;
use App\Repositories\RoleRepository;
use App\Repositories\UserRepository;
use App\Services\UserScoreService\UserScoreService;
use App\User;
use function GuzzleHttp\Psr7\str;
use Illuminate\Http\Request;

class ContactController extends BaseAPIController
{
    /**
     * @var RoleRepository
     */
    protected $ContactRepository;
    protected $contact;

    protected $userRepository;
    protected $scoreService;

    /**
     * @var UserRepository
     */

    public function __construct(AppRepository $appRepository,UserRepository $userRepository,UserScoreService $scoreService)
    {
        $this->appRepository = $appRepository;
        $this->model = new Contact();

        $this->person = new Person();
        $this->userRepository = $userRepository;
        $this->scoreService =$scoreService;
    }

    public function list()
    {
        return $this->model::select('id','first_name', 'last_name')->get();
    }

    public function index()
    {
//        return $this->model->orderBy('id', 'desc')->paginate();
//        $data =  parent::dataTables(,,);
        $columns =['first_name','user_id', 'last_name', 'mobile', 'email', 'tell','personal_code'];
        $search_column=['first_name','user_id', 'last_name', 'mobile', 'email', 'tell'];
        $with=['user'];
        if (!$search_column)
            $search_column = $columns;
        if ( \request()->input('showdata') ) {
            return $this->model::orderBy('created_at', 'desc')->get();
        }
        $length = \request()->input('length',15);
        $column = \request()->input('column');
        $order = \request()->input('order','desc');
        $search_input = \request()->input('search');
        $query = $this->model::select(array_merge($columns,['id','created_at']))
            ->orderBy($columns[$column]??'id',$order);
        if ($with)
            $query->with($with)->doesnthave('user.person');
        if ($search_input) {
            $query->where(function($query) use ($search_input,$search_column) {

                foreach ($search_column as $key => $column)
                    if ($key == array_key_first($search_column))
                        $query->where($column, 'like', '%' . $search_input . '%');
                    else
                        $query->orWhere($column, 'like', '%' . $search_input . '%');
//                    ->orWhere('mobile', 'like', '%' . $search_input . '%')
//                    ->orWhere('email', 'like', '%' . $search_input . '%')
//                    ->orWhere('tell', 'like', '%' . $search_input . '%');
//                    ->orWhere('created_at', 'like', '%' . $search_input . '%');
            });
        }
        $data = $query->paginate($length);
        $data->getCollection()->transform(function ($value) {
            $value->score = 0;
            if ($value->user)
            $value->score = $this->scoreService->getScore($value->user);
            return $value;
        });
        return $data;
        return parent::index(); // TODO: Change the autogenerated stub
    }


    public function show($id)
    {
        $data = Contact::where('id',$id)
            ->with(['user.orders','user.orders.OrderServices','user.orders.OrderServices.person','user.orders.OrderServices.service','user','group','tags','reviews'])
            ->first();
        $data->score = $this->scoreService->getScore($data->user);
        return $this->response($data);
    }


    public function store()
    {


        request()->validate([
            ////////// user validation ////////////////
            'first_name'=>['required'],
            'last_name'=>['required'],
//            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'mobile' => ['required', 'string', 'digits:11', 'unique:contacts', 'unique:users'],
//            'password' => ['required', 'string', 'min:8']
]);
        $user =$this->userRepository->add(\request());
        \request()->request->add(['created_by' => auth()->id(),'user_id' => $user->id]);
        \request()->validate($this->validationRules(),$this->validationMessages(),$this->validationAttributes());
        $data = $this->appRepository->add(\request()->all() , $this->model);
        $data->personal_code = generateRandomString(abs(5-strlen((string)$data->id)),'0123456789').$data->id;
        $data->save();
        $this->assignTags($data,\request()->tags);
        return $this->response($data);
    }

    public function update($id)
    {
        $contact = Contact::findOrFail($id);
        \request()->validate($this->validationRules(),$this->validationMessages(),$this->validationAttributes());
        $user =$this->userRepository->update(\request(),$contact->user_id);
        $data = $this->appRepository->edit(\request()->all() , $id, $this->model);
        if ($user->person)
            $this->appRepository->edit(\request()->all() , $user->person->id, new Person());
        $this->DeleteTags($id);
        $this->assignTags($data,\request()->tags);
        return $this->response($data);
    }


    protected function validationRules()
    {
        return [

            'first_name'=>['string','required'],
            'last_name'=>['string','required'],
            'mobile'=>['string','required'],
            'group_id'=>['nullable','exists:contact_groups,id'],
//            'email'=>['string','required'],
//            'image'=>['image'],



        ];
    }


    public  function assignTags($contact,$tags)
    {
        $contactTags=[];
        foreach ($tags??[] as $tag){
            $tag_id = CTag::FindOrCreate($tag);
            $contactTags[]=[
               'tag_id' => $tag_id,
               'contact_id' => $contact->id,
            ];
        }
        return ContactTag::insert($contactTags);
    }
    public  function DeleteTags($contact_id)
    {

        return ContactTag::where('contact_id',$contact_id)->delete();
    }

    public function FindByNumber($number)
    {
        $contact =Contact::where('mobile',"LIKE",'%'.$number.'%')->first();
        if (!$contact)
            $contact =Contact::where('tell',"LIKE",'%'.$number.'%')->first();

        return $this->response($contact);

    }

}
