<?php

namespace App\Http\Controllers;

use App\ProductDiscount;
use App\Repositories\AppRepositoryImpl;
use Illuminate\Http\Request;

class ProductDiscountController extends BaseAPIController
{
    public function __construct(AppRepositoryImpl $appRepository)
    {
        $this->appRepository = $appRepository;
        $this->model = new ProductDiscount();
    }
    protected function validationRules()
    {
        return [
            'product_id' => ['required','exists:products,id'],
            'discount_id' => ['required','exists:discounts,id']
        ];
    }

    protected function validationAttributes()
    {
        return parent::validationAttributes(); // TODO: Change the autogenerated stub
    }

    protected function validationMessages()
    {
        return parent::validationMessages(); // TODO: Change the autogenerated stub
    }

}
