<?php

namespace App\Http\Controllers;

use App\Repositories\AppRepositoryImpl;
use App\VacationDate;
use Illuminate\Http\Request;

class VacationDateController  extends BaseAPIController
{
    public function __construct(AppRepositoryImpl $appRepository)
    {
        $this->appRepository = $appRepository;
        $this->model = new VacationDate();
    }
    public function index()
    {
        return $this->model::paginate()->getCollection()->transform(function ($value) {
            $value->date = to_jalali_date($value->date);
            return $value;
        });
    }
    public function show($id)
    {
        $data = $this->model::findOrFiail($id);
        $data->date = to_jalali_date($data->date);
        return $this->response($data);
    }
    public function store()
    {
        \request()->request->set('date' , to_georgian_date(\request('date')));
        return parent::store(); // TODO: Change the autogenerated stub
    }

    protected function validationRules(){
        return [
            'title'=>[],
            'date'=>['required', function ($attribute, $value, $fail) {
                if (!validate_jalili($value)) {
                    $fail($attribute.' is not jalili time.');
                }
            }],
        ];
    }
    protected function validationAttributes(){
        return [];
    }
    protected function validationMessages(){
        return [];
    }
}